### ISSUE TITLE
Logo/Icon Design For App Manager Android

### ISSUE THREAD

**Issue by zularizal** [BharathVishal/App-Manager-Android#1]
Hi @BharathVishal , I am a graphic designer, I want to help others in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. It's free for your project. What do you think?

**Comment by BharathVishal** [comment]
Sounds good. Thanks for your proposal. Feel free to design a logo if you want to design a logo for free.

**Comment by zularizal** [comment]
Hi, i've designed some logos for you, what do you think? which one do you like?
If there is something you want to change, please let me know

![logo](https://user-images.githubusercontent.com/38547278/42120195-4b747d7a-7c41-11e8-8822-3cfae2e5c811.png)

**Comment by BharathVishal** [comment]
Hi, 
The second logo seems perfect. 👍

**Comment by zularizal** [comment]
Hi, I already uploaded the logo to drive, check this link

https://drive.google.com/open?id=1HMCfJiB3WTPeL-eqE-gGvyMNEUPblaM_

and also I have sent a pull request for you #2

**Comment by BharathVishal** [comment]
Hi, 
I have merged the pull request and added your name in the readme.md for logo designing. Thanks @zularizal . I'll close this issue now. 👍

**Comment by zularizal** [comment]
It's My pleasure :smile:
